### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by eightsixeight** [sipwise/db-schema#1]
seems a problem with interfaces on install ?

```
--> nagios
--> ldap
--> voisniff
--> prosody
--> debian-sys-maint
--> rsyslog
--> rateomat
--> dbcleaner
--> mediator
--> kamailioro
--> sems_prepaid
--> rtcengine
--> rtpengine
--> licensed
--> asterisk
--> exporter
--> fileshare
--> kamailio
--> soap
--> replicator
Done
Executing ngcp-influxdb-create to generate InfluxDB databases
Waiting for influxdb to start (59 seconds)...
Applying configuration
  - [/hosts/self/ens3] Expected required key 'type'
2018-12-02 20:08:48 vps215100: Error: Invalid schema detected for /etc/ngcp-config/network.yml
2018-12-02 20:08:48 vps215100: Error: Aborted, please fix issue(s) above and repeat.
ABORTED: Can not apply configuration
Please check log files for more information: /var/log/ngcp-installer.log
```

a cat of /etc/ngcp-config/network.yml
```
 cat /etc/ngcp-config/network.yml
---
hosts:
  self:
    dbnode: '1'
    ens3:
      dns_nameservers:
      - 192.168.1.1
      - 8.8.8.8
      gateway: 207.12.1.1
      hwaddr: fa:16:3e:b6:a5:36
      ip: 207.12.1.226
      netmask: 255.255.255.255
    interfaces:
    - lo
    - ens3
    lo:
      cluster_sets:
      - default
      ip: 127.0.0.1
      netmask: 255.255.255.0
      shared_ip: []
      shared_v6ip: []
      type:
      - sip_int
      - ha_int
      - web_ext
      - sip_ext
      - rtp_ext
      - web_int
      - aux_ext
      - ssh_ext
      - api_int
      - rtp_int
      - stor_int
      v6ip: ::1
      v6netmask: 128
    role:
    - proxy
    - lb
    - mgmt
    - rtp
    - db
    - storage
    status: online
    swraiddevices: []
```

**Comment by taurus-forever** [comment]
Hi,

Thank you for the bug report here. The error message you have is related to YML config files validation  which are part of repository https://github.com/sipwise/ngcpcfg. It is not related to the current db-schema repository.

Anyway, YML validation is mandatory part of mr6.5+ releases which helps ngcpcfg+templates generate proper config files. The error message reported by validation is:
```
> [/hosts/self/ens3] Expected required key 'type'
```
Which means "type:[]" declaration is missing for the interface.
On CE edition it is typical:
```
      type:
      - web_ext
      - ssh_ext
      - ...
``` 
You can find more information about all possible types here https://www.sipwise.org/doc/mr6.5.2/spce/?_href=ar01s12.html#_interface_parameters

Feel free to report such issues to Sipwise mailing list next time: https://lists.sipwise.com/pipermail/spce-user/

**Comment by eightsixeight** [comment]
i get that, i meant to show that your initial install messes up the interface services...
as you see it put all the ext on the lo interfaces..

so it crapped out the ngcp-initial-configuration which i can't rerun or it fails on shemas already existing.

Also...
from ngcp-clish
```
# show ngcp registrations 
lua: /usr/share/lua/5.1/ngcp-klish/configs.lua:51: Failed to connect to database: Access denied for user 'soap'@'localhost' (using password: YES)
stack traceback:
        [C]: in function 'assert'
        /usr/share/lua/5.1/ngcp-klish/configs.lua:51: in function 'get_connection'
        /usr/share/lua/5.1/ngcp-klish/configs.lua:60: in function 'get_users'
        /usr/share/lua/5.1/ngcp-klish/ngcp.lua:269: in function 'reg_stats'
        stdin:1: in main chunk
```

**Comment by eightsixeight** [comment]
is there a way to repush the initial config ?
as right now i dont have anything listening opn port 5060.. only 5062 etc..

**Comment by taurus-forever** [comment]
> i get that, i meant to show that your initial install messes up the interface services...

I never saw your situation after ngcp-installer out-of-the-box.

> as you see it put all the ext on the lo interfaces..

Yes, I saw it. It is fine. By default they should be there. All other interfaces should receive 
```
type: []
```

> is there a way to repush the initial config ?

Just add missing 'type: []' and execute: ngcpcfg apply --force-all-services "applying network.yml changes"

> so it crapped out the ngcp-initial-configuration which i can't rerun or it fails on shemas already existing.

Please describe the steps you performed, how did you install CE?
BTW, what is the NGCP version you are using?
I would like to have it traced and fixed if necessary.
Can you please share the /var/log/ngcp-installer.log with me directly?

> Also... from ngcp-clish

I suspect final configuration was not accomplished on your side, not all the components running. 
Checked the same command on my side:
```
root@spce:~# ngcp-clish
Entering 'clish-enable' view (press Ctrl+Z to exit)...
# show ngcp registrations
Users: 49
Users online: 7
Users offline: 42
# 
```

Also I can hint you to use 'ngcp-service summary' to see missing services
and the script 'ngcp-usr-location' which can report registered devices for both MySQL and Redis backends. We need to finish your installation first.

**Comment by taurus-forever** [comment]
I was able to reproduce your problem locally.

The issue is here https://github.com/sipwise/ngcpcfg/blob/master/sbin/ngcp-network-validator#L165
All Sipwise Jenkins test installations operates with interfaces eth0/eth1/... and there we have special handling for such interfaces in line 155 which hides the issues for us internally.
In your case the interface name is 'ens3'.
The bug was sleeping there until we enabled YML validation in mr6.5+

Reported internally as TT#48194 and preparing the fix,
which will create empty 'type: []' for all interfaces where it is missing.
Please stay tuned.

P.S. As a workaround you can add 'type: []' and perform apply as I wrote above.

**Comment by taurus-forever** [comment]
The issue has been fixed and new packages were released for mr6.5.1+,
please consider to repeat your installation, you should have no errors there.

Thank you for the bugreport once again. Have fun!

**Comment by mmuhd** [comment]
Please I have issue similar to this, but slightly different, this is what it is outputting.
```
 - [/hosts/self/eth0] Expected required key 'hwaddr'
2021-02-23 19:01:50 ip-: Error: Invalid schema detected for /etc/ngcp-config/network.yml
2021-02-23 19:01:50 ip-: Error: Aborted, please fix issue(s) above and repeat.
```
I tried this on C5 mr.9.2.1 and 8.5.3
Thank you in advance

**Comment by mika** [comment]
@mmuhd looks like you are jumping from https://github.com/sipwise/ngcpcfg/issues/1 here? Please fix your `/etc/ngcp-config/network.yml` by adding an `hwaddr` entry, just as the error message tells you.

**Comment by mmuhd** [comment]
Oh I got it thanks @mika I resolved it by adding the hwaddr at /etc/ngcp-config/network.yml. Now everything is fine, Thanks a lot.
